<html>

<head>
	<meta charset="utf-8" />
	<title>Miniframework</title>
	<link rel="stylesheet" href="/assets/style.css">
	<link href="https://cdn.quilljs.com/1.3.6/quill.snow.css" rel="stylesheet">
	<script src="https://cdn.jsdelivr.net/npm/alpinejs@3.x.x/dist/cdn.min.js" defer></script>
	<script src="https://cdn.quilljs.com/1.3.6/quill.min.js"></script>
</head>

<body>
	<div x-data="{ sidebarOpen: false }" class="flex h-screen bg-gray-200 font-roboto">
		<div x-cloak :class="sidebarOpen ? 'translate-x-0 ease-out' : '-translate-x-full ease-in'" class="fixed inset-y-0 left-0 z-30 w-64 overflow-y-auto transition duration-300 transform bg-gray-900 lg:translate-x-0 lg:static lg:inset-0">
			<div class="flex items-center justify-center mt-8">
				<div class="flex items-center">
					<img src="/assets/logo.png" alt="Estação 1" class="w-[80%] max-w-full mx-auto brightness-0 invert pointer-events-none">
				</div>
			</div>

			<nav class="mt-10">
				<a class="flex items-center px-6 py-2 mt-4 text-gray-500 hover:bg-gray-700 hover:bg-opacity-25 hover:text-gray-100" href="./">
					<svg class="w-6 h-6" xmlns="http://www.w3.org/2000/svg" fill="none" viewBox="0 0 24 24" stroke="currentColor">
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M11 3.055A9.001 9.001 0 1020.945 13H11V3.055z" />
						<path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M20.488 9H15V3.512A9.025 9.025 0 0120.488 9z" />
					</svg>

					<span class="mx-3">Dashboard</span>
				</a>

				<a class="flex items-center px-6 py-2 mt-4 text-gray-500 hover:bg-gray-700 hover:bg-opacity-25 hover:text-gray-100" href="./blog">

					<svg xmlns="http://www.w3.org/2000/svg" class="w-6 h-6" fill="currentColor" viewBox="0 0 16 16">
						<path d="M14.5 3a.5.5 0 0 1 .5.5v9a.5.5 0 0 1-.5.5h-13a.5.5 0 0 1-.5-.5v-9a.5.5 0 0 1 .5-.5h13zm-13-1A1.5 1.5 0 0 0 0 3.5v9A1.5 1.5 0 0 0 1.5 14h13a1.5 1.5 0 0 0 1.5-1.5v-9A1.5 1.5 0 0 0 14.5 2h-13z" />
						<path d="M3 5.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM3 8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9A.5.5 0 0 1 3 8zm0 2.5a.5.5 0 0 1 .5-.5h6a.5.5 0 0 1 0 1h-6a.5.5 0 0 1-.5-.5z" />
					</svg>

					<span class="mx-3">Blog</span>
				</a>
			</nav>
		</div>

		<div class="flex-1 flex flex-col overflow-hidden">
			<main class="flex-1 overflow-x-hidden overflow-y-auto bg-gray-200">
				<div class="container mx-auto px-6 py-8">
					<?= $this->content() ?>
				</div>
			</main>
		</div>
	</div>
	<script src="/assets/main.js"></script>
</body>

</html>